# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "http://localhost:3000/socket.io/?EIO=4&transport=polling&t=OhZyNgz"
  force = true
  headers = {X-From = "Netlify"}
  [[headers]]
  for = "/"
  [headers.values]
  Access-Control-Allow-Origin = "*"

