# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "https://my-draw-board.netlify.app/"
  force = true
  headers = {X-From = "Netlify"}
  [[headers]]
  for = "/"
  [headers.values]
  Access-Control-Allow-Origin = "*"

