[[redirects]]
from = "/api/"
to = "https://my-draw-board.netlify.app/socket.io"
status = 200
force = true
headers = {X-From = "Netlify"}
[[headers]]
for = "/"
[headers.values]
Access-Control-Allow-Origin = "*"

